// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDCu4tQz9MlbSSU2L1CTp3hDA6wpIXWs',
    appId: '1:763774998716:web:d88efc74c43c0ab5d918b9',
    messagingSenderId: '763774998716',
    projectId: 'planit-4a12c',
    authDomain: 'planit-4a12c.firebaseapp.com',
    storageBucket: 'planit-4a12c.appspot.com',
    measurementId: 'G-6HNPVPZT42',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_4WApK8tvjP6MUVAEtZnQnLUt1nSqPu0',
    appId: '1:763774998716:android:871f5cf90710cc95d918b9',
    messagingSenderId: '763774998716',
    projectId: 'planit-4a12c',
    storageBucket: 'planit-4a12c.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGDCu4tQz9MlbSSU2L1CTp3hDA6wpIXWs',
    appId: '1:763774998716:web:0a6e55b3def2a41bd918b9',
    messagingSenderId: '763774998716',
    projectId: 'planit-4a12c',
    authDomain: 'planit-4a12c.firebaseapp.com',
    storageBucket: 'planit-4a12c.appspot.com',
    measurementId: 'G-QRER3V03V4',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbj2W4oAYTiffEdiy9kDuuB8jRuev75v4',
    appId: '1:763774998716:ios:e4d86246faecf586d918b9',
    messagingSenderId: '763774998716',
    projectId: 'planit-4a12c',
    storageBucket: 'planit-4a12c.appspot.com',
    iosBundleId: 'com.example.planit',
  );

}